[package]
name = "kimchi"
version = "0.1.0"
authors = ["Warren Galyen <wgalyen@bellhelmets.com>"]
edition = "2018"
description = "A spicy link checker"
homepage = "https://github.com/wgalyen/kimchi"
repository = "https://github.com/wgalyen/kimchi"
documentation = ""
license = "Apache-2.0/MIT"

[dependencies]
any = "*"
anyhow = "*"
futures = "0.3"
github-rs = "0.7.0"
gumdrop = "*"
linkify = "*"
url = "2.1.1"
log = "0.4"
pretty_env_logger = "0.4"
pulldown-cmark = "0.7.2"
regex = "*"
serde_json = "1.0.56"

[dependencies.reqwest]
features = ["gzip"]
version = "0.10"

[dependencies.tokio]
features = ["full"]
version = "0.2"