[package]
name = "kimchi"
version = "0.2.0"
authors = ["Warren Galyen <wgalyen@bellhelmets.com>"]
edition = "2018"
description = "A spicy link checker"
homepage = "https://github.com/wgalyen/kimchi"
repository = "https://github.com/wgalyen/kimchi"
documentation = ""
license = "Apache-2.0/MIT"

[dependencies]
anyhow = "1.0.32"
futures = "0.3"
glob = "0.3.0"
gumdrop = "0.8.0"
http = "0.2"
hubcaps = "0.6"
linkify = "0.4.0"
url = "2.1.1"
log = "0.4"
pretty_env_logger = "0.4"
pulldown-cmark = "0.7.2"
regex = "1.3.9"
serde_json = "1.0.56"

[dependencies.reqwest]
features = ["gzip"]
version = "0.10"

[dependencies.tokio]
features = ["full"]
version = "0.2"