[package]
name = "kimchi"
version = "0.6.0"
authors = ["Warren Galyen <wgalyen@bellhelmets.com>"]
edition = "2018"
description = "A spicy link checker"
homepage = "https://github.com/wgalyen/kimchi"
keywords = [
    "link",
    "checker",
    "cli",
    "link-checker",
    "validator",
]
repository = "https://github.com/wgalyen/kimchi"
documentation = ""
license = "Apache-2.0/MIT"

[dependencies]
anyhow = "1.0.38"
futures = "0.3.12"
glob = "0.3.0"
http = "0.2.3"
# Switch back to version on crates.io after 0.6.3+ is released
hubcaps = { git="https://github.com/softprops/hubcaps.git" }
linkify = "0.5.0"
regex = "1.4.3"
url = "2.2.0"
# Switch back to version on crates.io after
# https://github.com/async-email/async-smtp/pull/36
# is merged and a new version of check-if-email-exists is released
check-if-email-exists = { git="https://github.com/reacherhq/check-if-email-exists.git" }
indicatif = "0.15.0"
structopt = "0.3.21"
toml = "0.5.8"
serde = { version = "1.0.123", features = ["derive"] }
pulldown-cmark = "0.8.0"
html5ever = "0.25.1"
markup5ever = "0.10.0"
markup5ever_rcdom = "0.1.0"
headers = "0.3.3"
derive_builder = "0.9.0"
deadpool = "0.7.0"
shellexpand = "2.1.0"
lazy_static = "1.4.0"
wiremock = "0.4.9"
openssl-sys = "0.9.60"
serde_json = "1.0.62"
# Make build work on Apple Silicon.
# See https://github.com/briansmith/ring/issues/1163
# This is necessary for the homebrew build
# https://github.com/Homebrew/homebrew-core/pull/70216
ring = "0.16.19"
pad = "0.1.6"
console = "0.14.0"

[dependencies.reqwest]
features = ["gzip"]
version = "0.11.0"

[dependencies.tokio]
features = ["full"]
version = "1.2.0"

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1.0.7"
uuid = { version = "0.8.2", features = ["v4"] }
tempfile = "3.2.0"

[features]
vendored-openssl = ["openssl-sys/vendored"]
